<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 
$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
 
// get san pham theo ID
$product = $productRepository->getById(5);
 
// get san pham theo sku 
$product = $productRepository->get('MT12');
 
echo $product->getEntityId() . '<br>';
echo $product->getName() . '<br>';
echo $product->getSKU() . '<br>';
echo $product->getPrice() . '<br>';
echo $product->getSpecialPrice() . '<br>';
echo $product->getTypeId() . '<br>';
echo $product->getProductUrl() . '<br>';
 ?>