<div class="footer-container ">
    <div class="footer">
        <div class="footer-middle">
        	<div class="container">
                <div class="row">
                	<div class="col-sm-3">
                		<div class="row">
							<div class="col-sm-12">
								<div class="block">
									<div class="block-title"><strong><span>Store Information</span></strong></div>
									<div class="block-content">
										<ul class="links">
											<li><em class="icon-right-dir theme-color"></em><a href="/web/20180618045209/https://www.macfixit.com.au/about-us">ABOUT US</a></li>
											<li><em class="icon-right-dir theme-color"></em><a href="http://web.archive.org/web/20180618045209/http://support.macfixit.com.au/">QUESTIONS &amp; HELP</a></li>
											<li><em class="icon-right-dir theme-color"></em><a href="http://web.archive.org/web/20180618045209/http://support.macfixit.com.au/article/7-shipping-charges-delivery-times">SHIPPING &amp; DELIVERY TIMES</a></li>
											<li><em class="icon-right-dir theme-color"></em><a href="http://web.archive.org/web/20180618045209/http://support.macfixit.com.au/article/37-privacy-policy-cookies">PRIVACY POLICY</a></li>
											<li><em class="icon-right-dir theme-color"></em><a href="http://web.archive.org/web/20180618045209/http://support.macfixit.com.au/article/38-terms-and-conditions">TERMS AND CONDITIONS</a></li>
											<li><em class="icon-right-dir theme-color"></em><a href="http://web.archive.org/web/20180618045209/http://support.macfixit.com.au/article/39-reseller-enquiries">RESELLER ENQUIRIES</a></li>
											<li><em class="icon-right-dir theme-color"></em><a href="http://web.archive.org/web/20180618045209/http://support.macfixit.com.au/article/17-do-you-accept-purchase-orders-do-you-accept-school-or-government-orders">EDUCATION &amp; GOVERNMENT PURCHASING</a></li>
											<li><em class="icon-right-dir theme-color"></em><a href="/web/20180618045209/https://www.macfixit.com.au/contacts">CONTACT US</a></li>
											<li><em class="footer_payment_accepted"></em></li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>               
					<div class="col-sm-3">
						<div class="block">
							<div class="block-title"><strong><span>Contact Information</span></strong></div>
							<div class="block-content">
								<ul class="contact-info">
									<li><em class="icon-location">&nbsp;</em><strong>CLICKSPOT PTY LTD (T/A MACFIXIT AUSTRALIA)</strong><br>
									<p><span>OFFICE 3/250 BARKLY STREET</span><br><span>FOOTSCRAY 3011<br><br><span>PLEASE NOTE: There is no pick-up/over the counter service at our office address.</span></span></p>
									</li>
									<li><em class="icon-phone">&nbsp;</em>
									<p><strong>Phone:</strong><br>03 9329 4343</p>
									</li>
									<li><em class="icon-clock">&nbsp;</em>
									<p><strong>Opening Hours:</strong><br>Mon - Fri / 10AM - 5.30PM</p>
									</li>
									<li>
									<p><span>ACN:&nbsp;617 849 386</span><br><span>ABN:&nbsp;33 617 849 386</span></p>
									</li>
								</ul>
							</div>
						</div>
					</div>                    
					<div class="col-sm-3">
						<div class="block">
							<div class="block-title"><strong><span>Why shop with us?</span></strong></div>
							<div class="block-content">
								<ul class="features">
									<li><em class="icon-ok  theme-color"></em><strong>30 Day Money Back Guarantee</strong></li>
									<li><em class="icon-ok  theme-color"></em><strong>$9.90 Flat Rate Shipping for any size order</strong></li>
									<li><em class="icon-ok  theme-color"></em><strong>Convenient and secure shopping</strong></li>
									<li><em class="icon-ok  theme-color"></em><strong>Awesome customer service</strong></li>
									<li><em class="icon-ok  theme-color"></em><strong>Over 500,000 orders shipped since 2005</strong></li>
								</ul>
							</div>
						</div>
					</div>                   
					<div class="col-sm-3">
						<div class="block block-subscribe">
						    <div class="block-title">
						        <strong><span>STAY IN THE KNOW</span></strong>
						    </div>
						    <form action="">
						        <div class="block-content">
						            <p>Subscribe to the Macfixit Australia newsletter and be the first to know about new product launches, events and special offers.</p>
						            <div class="input-box">
						                <p class="label">Enter your e-mail Address</p>
						                <input type="text" name="email" id="newsletter_footer" title="Sign up for our newsletter" class="input-text required-entry validate-email">
						                <button type="submit" title="Submit" class="button"><span><span>Submit</span></span></button>
						                <div class="clearer"></div>
						            </div>
						        </div>
						    </form>
						</div>
						<div class="block-image-ft">
							<div class="footer_mcafee_verified" style="float: right;"></div>
							<!--div class="footer_norton_verified"></div-->
						</div>
					</div>           
            		<div class="footer-bottom">
            			<div class="container">
                            <a href="http://web.archive.org/web/20180618045209/https://www.macfixit.com.au/" class="logo"></a>
                            <div class="footer-social-icons">
								<a href="#" class="fa fa-facebook fa-lg" title="Facebook" target="_blank"></a>
								<a href="#" class="fa fa-twitter fa-lg" title="Twitter" target="_blank"></a>
							</div>
                			<div class="custom-block"><</div>
                			<div class="custom-block f-right"></div>
                			<address>© Copyright 2005-2018 Clickspot Pty Ltd/Macfixit Australia Pty Ltd.</address>
                         </div>
     				</div>
				</div>
			</div>
		</div>
	</div>
</div>