<form class="form" action="<?php echo $block->getFormAction() ?>" method="post">

    <fieldset class="fieldset">
        <legend class="legend"><span><?php  echo __('Add new comment') ?></span></legend><br>
        <div class="field required">
            <label for="user_id" class="label">
                <span><?php echo __('ID') ?></span>
            </label>
            <div class="control">
                <input type="text" id="user_id" name="user_id" class="input-text" width="50%">
            </div>
        </div>
        <div class="field required">
            <label for="comment" class="label">
                <span><?php echo __('Content') ?></span>
            </label>
            <div class="control">
                <textarea id="comment" name="comment" class="input-text"></textarea>
            </div>
        </div>
    </fieldset>
    <input type="hidden" name="post_id" value="<?php echo $block->getPostID() ?>"/>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?php echo __('Submit') ?>">
                <span><?php  echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>